package itson.ticketwizard.presentacion;

import itson.ticketwizard.control.ControlRegistrarCompra;

/**
 *
 * @author victoria
 */
public class FrmHistorialBoletos extends javax.swing.JFrame {
     private final ControlRegistrarCompra control;
    
    /**
     * Creates new form FrmHistorialBoletos
     */
    public FrmHistorialBoletos(ControlRegistrarCompra control) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.control = control;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtVolverMenu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBoletos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(223, 218, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Galvji", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(95, 84, 163));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mis Boletos");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 410, 90));

        txtVolverMenu.setBackground(new java.awt.Color(119, 118, 126));
        txtVolverMenu.setFont(new java.awt.Font("Galvji", 1, 18)); // NOI18N
        txtVolverMenu.setForeground(new java.awt.Color(255, 255, 255));
        txtVolverMenu.setText("Regresar al menú");
        jPanel2.add(txtVolverMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 200, 40));

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setBackground(new java.awt.Color(223, 218, 255));

        tblBoletos.setFont(new java.awt.Font("Galvji", 0, 24)); // NOI18N
        tblBoletos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código Boleto", "Nombre Evento", "Fecha Evento", "Recinto", "Asiento", "Ciudad", "Estado", "Descripción", "Número Transacción", "FechaHora Compra", "Forma Compra"
            }
        ));
        jScrollPane1.setViewportView(tblBoletos);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBoletos;
    private javax.swing.JButton txtVolverMenu;
    // End of variables declaration//GEN-END:variables
}
