/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package itson.ticketwizard.presentacion;

/**
 *
 * @author victoria
 */
public class FrmMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenuPrincipal
     */
    public FrmMenuPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl1 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btmAgregarSaldo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnComprarBoleto = new javax.swing.JButton();
        btnVenderBoleto = new javax.swing.JButton();
        btnVerBoletos = new javax.swing.JButton();
        btnVerHistorialCompras = new javax.swing.JButton();
        btnVerHistorialVentas = new javax.swing.JButton();
        btnVerBoletosApartados = new javax.swing.JButton();
        btnVerDepositos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl1.setBackground(new java.awt.Color(221, 210, 234));
        pnl1.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(175, 169, 209));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoPequeno1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 260, 280));

        btnCerrarSesion.setBackground(new java.awt.Color(95, 84, 163));
        btnCerrarSesion.setFont(new java.awt.Font("Galvji", 1, 18)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setText("Cerrar Sesión");
        jPanel1.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 180, 50));

        btnActualizar.setBackground(new java.awt.Color(95, 84, 163));
        btnActualizar.setFont(new java.awt.Font("Galvji", 1, 18)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar Perfil");
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 180, 50));

        btmAgregarSaldo.setBackground(new java.awt.Color(95, 84, 163));
        btmAgregarSaldo.setFont(new java.awt.Font("Galvji", 1, 18)); // NOI18N
        btmAgregarSaldo.setForeground(new java.awt.Color(255, 255, 255));
        btmAgregarSaldo.setText("Agregar Saldo");
        jPanel1.add(btmAgregarSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 180, 50));

        pnl1.add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel2.setBackground(new java.awt.Color(223, 218, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Galvji", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(95, 84, 163));
        jLabel2.setText("Bienvenido");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 290, 80));

        btnComprarBoleto.setBackground(new java.awt.Color(119, 118, 126));
        btnComprarBoleto.setFont(new java.awt.Font("Galvji", 1, 18)); // NOI18N
        btnComprarBoleto.setForeground(new java.awt.Color(255, 255, 255));
        btnComprarBoleto.setText("Comprar Boletos");
        jPanel2.add(btnComprarBoleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 390, 50));

        btnVenderBoleto.setBackground(new java.awt.Color(119, 118, 126));
        btnVenderBoleto.setFont(new java.awt.Font("Galvji", 1, 18)); // NOI18N
        btnVenderBoleto.setForeground(new java.awt.Color(255, 255, 255));
        btnVenderBoleto.setText("Vender Boletos");
        jPanel2.add(btnVenderBoleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 390, 50));

        btnVerBoletos.setBackground(new java.awt.Color(119, 118, 126));
        btnVerBoletos.setFont(new java.awt.Font("Galvji", 1, 18)); // NOI18N
        btnVerBoletos.setForeground(new java.awt.Color(255, 255, 255));
        btnVerBoletos.setText("Ver Mis Boletos");
        jPanel2.add(btnVerBoletos, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 390, 50));

        btnVerHistorialCompras.setBackground(new java.awt.Color(119, 118, 126));
        btnVerHistorialCompras.setFont(new java.awt.Font("Galvji", 1, 18)); // NOI18N
        btnVerHistorialCompras.setForeground(new java.awt.Color(255, 255, 255));
        btnVerHistorialCompras.setText("Consultar Historial de Compras");
        jPanel2.add(btnVerHistorialCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 390, 50));

        btnVerHistorialVentas.setBackground(new java.awt.Color(119, 118, 126));
        btnVerHistorialVentas.setFont(new java.awt.Font("Galvji", 1, 18)); // NOI18N
        btnVerHistorialVentas.setForeground(new java.awt.Color(255, 255, 255));
        btnVerHistorialVentas.setText("Consultar Historial de Ventas");
        jPanel2.add(btnVerHistorialVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 390, 50));

        btnVerBoletosApartados.setBackground(new java.awt.Color(119, 118, 126));
        btnVerBoletosApartados.setFont(new java.awt.Font("Galvji", 1, 18)); // NOI18N
        btnVerBoletosApartados.setForeground(new java.awt.Color(255, 255, 255));
        btnVerBoletosApartados.setText("Mis Boletos Apartados");
        jPanel2.add(btnVerBoletosApartados, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, 390, 50));

        btnVerDepositos.setBackground(new java.awt.Color(119, 118, 126));
        btnVerDepositos.setFont(new java.awt.Font("Galvji", 1, 18)); // NOI18N
        btnVerDepositos.setForeground(new java.awt.Color(255, 255, 255));
        btnVerDepositos.setText("Consultar Historial de Depósitos");
        jPanel2.add(btnVerDepositos, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 390, 50));

        pnl1.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmAgregarSaldo;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnComprarBoleto;
    private javax.swing.JButton btnVenderBoleto;
    private javax.swing.JButton btnVerBoletos;
    private javax.swing.JButton btnVerBoletosApartados;
    private javax.swing.JButton btnVerDepositos;
    private javax.swing.JButton btnVerHistorialCompras;
    private javax.swing.JButton btnVerHistorialVentas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pnl1;
    // End of variables declaration//GEN-END:variables
}
