package itson.ticketwizard.presentacion;

import itson.ticketwizard.control.ControlMenuPrincipal;
import itson.ticketwizard.dtos.UsuarioRegistradoDTO;

/**
 *
 * @author victoria
 */
public class FrmMenuPrincipal extends javax.swing.JFrame {
    private final ControlMenuPrincipal control;
    private UsuarioRegistradoDTO usuarioRegistradoDTO;

    /**
     * Creates new form FrmMenuPrincipal
     */
    public FrmMenuPrincipal(ControlMenuPrincipal control, UsuarioRegistradoDTO usuarioRegistradoDTO) {
        initComponents();
        this.control = control;
        this.usuarioRegistradoDTO = usuarioRegistradoDTO;
        this.setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl1 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btmAgregarSaldo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnBuscarBoleto = new javax.swing.JButton();
        btnVerBoletos = new javax.swing.JButton();
        btnVerHistorialCompras = new javax.swing.JButton();
        btnVerHistorialVentas = new javax.swing.JButton();
        btnVerBoletosApartados = new javax.swing.JButton();
        btnVerDepositos = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl1.setBackground(new java.awt.Color(221, 210, 234));
        pnl1.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(175, 169, 209));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoPequeno1.png"))); // NOI18N

        btnCerrarSesion.setFont(new java.awt.Font("Galvji", 1, 18)); // NOI18N
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        btnActualizar.setFont(new java.awt.Font("Galvji", 1, 18)); // NOI18N
        btnActualizar.setText("Actualizar Perfil");
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btmAgregarSaldo.setFont(new java.awt.Font("Galvji", 1, 18)); // NOI18N
        btmAgregarSaldo.setText("Agregar Saldo");
        btmAgregarSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmAgregarSaldoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btmAgregarSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btmAgregarSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );

        pnl1.add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel2.setBackground(new java.awt.Color(223, 218, 255));

        btnBuscarBoleto.setFont(new java.awt.Font("Galvji", 1, 18)); // NOI18N
        btnBuscarBoleto.setText("Buscar Boletos");
        btnBuscarBoleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarBoletoActionPerformed(evt);
            }
        });

        btnVerBoletos.setFont(new java.awt.Font("Galvji", 1, 18)); // NOI18N
        btnVerBoletos.setText("Ver Mis Boletos");
        btnVerBoletos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerBoletosActionPerformed(evt);
            }
        });

        btnVerHistorialCompras.setFont(new java.awt.Font("Galvji", 1, 18)); // NOI18N
        btnVerHistorialCompras.setText("Consultar Historial de Compras");
        btnVerHistorialCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerHistorialComprasActionPerformed(evt);
            }
        });

        btnVerHistorialVentas.setFont(new java.awt.Font("Galvji", 1, 18)); // NOI18N
        btnVerHistorialVentas.setText("Consultar Historial de Ventas");
        btnVerHistorialVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerHistorialVentasActionPerformed(evt);
            }
        });

        btnVerBoletosApartados.setFont(new java.awt.Font("Galvji", 1, 18)); // NOI18N
        btnVerBoletosApartados.setText("Mis Boletos Apartados");

        btnVerDepositos.setFont(new java.awt.Font("Galvji", 1, 18)); // NOI18N
        btnVerDepositos.setText("Consultar Historial de Depósitos");
        btnVerDepositos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerDepositosActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Galvji", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(95, 84, 163));
        jLabel3.setText("Bienvenido");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(btnBuscarBoleto, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(btnVerBoletos, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(btnVerHistorialCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(btnVerHistorialVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(btnVerDepositos, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(btnVerBoletosApartados, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(120, 120, 120))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(191, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(160, 160, 160)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(btnBuscarBoleto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVerBoletos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVerHistorialCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVerHistorialVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVerDepositos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(btnVerBoletosApartados, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(64, 64, 64)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(456, Short.MAX_VALUE)))
        );

        pnl1.add(jPanel2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl1, javax.swing.GroupLayout.PREFERRED_SIZE, 920, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        control.cerrarSesion();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        control.mostrarActualizarUsuario(this.usuarioRegistradoDTO);
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnBuscarBoletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarBoletoActionPerformed
        control.mostrarResultadosBusqueda(this.usuarioRegistradoDTO);
    }//GEN-LAST:event_btnBuscarBoletoActionPerformed

    private void btnVerHistorialComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerHistorialComprasActionPerformed
        control.mostrarHistorialCompras(this.usuarioRegistradoDTO);
    }//GEN-LAST:event_btnVerHistorialComprasActionPerformed

    private void btnVerHistorialVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerHistorialVentasActionPerformed
        control.mostrarHistorialReventas(this.usuarioRegistradoDTO);
    }//GEN-LAST:event_btnVerHistorialVentasActionPerformed

    private void btnVerBoletosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerBoletosActionPerformed
        control.mostrarMisBoletos(this.usuarioRegistradoDTO);
    }//GEN-LAST:event_btnVerBoletosActionPerformed

    private void btmAgregarSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmAgregarSaldoActionPerformed
        control.mostrarDepositoSaldo(this.usuarioRegistradoDTO);
    }//GEN-LAST:event_btmAgregarSaldoActionPerformed

    private void btnVerDepositosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerDepositosActionPerformed
        control.mostrarHistorialDepositos(this.usuarioRegistradoDTO);
    }//GEN-LAST:event_btnVerDepositosActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmAgregarSaldo;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscarBoleto;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnVerBoletos;
    private javax.swing.JButton btnVerBoletosApartados;
    private javax.swing.JButton btnVerDepositos;
    private javax.swing.JButton btnVerHistorialCompras;
    private javax.swing.JButton btnVerHistorialVentas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pnl1;
    // End of variables declaration//GEN-END:variables
}
