package itson.ticketwizard.presentacion;

/**
 *
 * @author victoria
 */
public class FrmResultadosBusqueda extends javax.swing.JFrame {

    /**
     * Creates new form FrmResultadosBusqueda
     */
    public FrmResultadosBusqueda() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCodigoBoleto = new javax.swing.JTextField();
        txtSeleccionar = new javax.swing.JButton();
        txtRegresarMenu = new javax.swing.JButton();
        pnlResultados = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(223, 218, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Galvji", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(95, 84, 163));
        jLabel1.setText("Resultados de la Búsqueda");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 500, 60));

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(223, 218, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Galvji", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(95, 84, 163));
        jLabel2.setText("Código del boleto");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, -1));
        jPanel3.add(txtCodigoBoleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 260, 40));

        txtSeleccionar.setBackground(new java.awt.Color(95, 84, 163));
        txtSeleccionar.setFont(new java.awt.Font("Galvji", 1, 18)); // NOI18N
        txtSeleccionar.setForeground(new java.awt.Color(255, 255, 255));
        txtSeleccionar.setText("Seleccionar");
        jPanel3.add(txtSeleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, 210, 40));

        txtRegresarMenu.setBackground(new java.awt.Color(119, 118, 126));
        txtRegresarMenu.setFont(new java.awt.Font("Galvji", 1, 18)); // NOI18N
        txtRegresarMenu.setForeground(new java.awt.Color(255, 255, 255));
        txtRegresarMenu.setText("Regresar al Menú");
        txtRegresarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegresarMenuActionPerformed(evt);
            }
        });
        jPanel3.add(txtRegresarMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 250, 40));

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Evento", "Fecha", "Recinto", "Asiento", "Ciudad", "Estado", "Precio"
            }
        ));
        pnlResultados.setViewportView(jTable1);

        jPanel2.add(pnlResultados, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRegresarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegresarMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegresarMenuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTable jTable1;
    private javax.swing.JScrollPane pnlResultados;
    private javax.swing.JTextField txtCodigoBoleto;
    private javax.swing.JButton txtRegresarMenu;
    private javax.swing.JButton txtSeleccionar;
    // End of variables declaration//GEN-END:variables
}
