package itson.ticketwizard.presentacion;

/**
 *
 * @author victoria
 */
public class FrmVenderBoleto extends javax.swing.JFrame {

    /**
     * Creates new form FrmCompraBoleto
     */
    public FrmVenderBoleto() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jrbBuscarNombreEvento = new javax.swing.JRadioButton();
        jrbBuscarRangoFechas = new javax.swing.JRadioButton();
        txtNombreEvento = new javax.swing.JTextField();
        txtFechaFin = new javax.swing.JFormattedTextField();
        txtFechaInicio = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnRegresarMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(57, 57, 57));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Galvji", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("a");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, -1, -1));

        jLabel2.setFont(new java.awt.Font("Galvji", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Vender Boleto");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, -1));

        jrbBuscarNombreEvento.setFont(new java.awt.Font("Galvji", 1, 18)); // NOI18N
        jrbBuscarNombreEvento.setForeground(new java.awt.Color(255, 255, 255));
        jrbBuscarNombreEvento.setText("Nombre del evento");
        jPanel1.add(jrbBuscarNombreEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, -1, -1));

        jrbBuscarRangoFechas.setFont(new java.awt.Font("Galvji", 1, 18)); // NOI18N
        jrbBuscarRangoFechas.setForeground(new java.awt.Color(255, 255, 255));
        jrbBuscarRangoFechas.setText("Rango de fechas");
        jPanel1.add(jrbBuscarRangoFechas, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, -1, -1));

        txtNombreEvento.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jPanel1.add(txtNombreEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 200, 30));

        txtFechaFin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yy"))));
        jPanel1.add(txtFechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, 100, 30));

        txtFechaInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yy"))));
        jPanel1.add(txtFechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, 100, 30));

        jLabel3.setFont(new java.awt.Font("Galvji", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Seleccione el método de búsqueda de boletos");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        btnBuscar.setBackground(new java.awt.Color(95, 84, 163));
        btnBuscar.setFont(new java.awt.Font("Galvji", 1, 18)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, 240, 50));

        btnRegresarMenu.setBackground(new java.awt.Color(119, 118, 126));
        btnRegresarMenu.setFont(new java.awt.Font("Galvji", 1, 18)); // NOI18N
        btnRegresarMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresarMenu.setText("Regresar al menú");
        jPanel1.add(btnRegresarMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 480, 310, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnRegresarMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jrbBuscarNombreEvento;
    private javax.swing.JRadioButton jrbBuscarRangoFechas;
    private javax.swing.JFormattedTextField txtFechaFin;
    private javax.swing.JFormattedTextField txtFechaInicio;
    private javax.swing.JTextField txtNombreEvento;
    // End of variables declaration//GEN-END:variables
}
